title: Flexa Group
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.flexagroup.co.uk
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC â€” Jan 2
  down: "#D70040"
  systems:
    - name: API
      description: The bots API services
      category: Core Services
    - name: Payments
      description: How we handle our payments
      category: Core Services
    - name: Core Functions
      category: Core Services
    - name: Website
      category: Core Services
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#3d96d9"
  enableLastMod: true
  headerTextColor: black
  logo: /img/flexa_logo.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#228B22"
  notice: "#1155cc"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Core Services
      closed: false
      untitled: true
      description: This shows all the core services we offer at Flexa Group
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
